### ISSUE TITLE
Use as Library

### ISSUE THREAD

**Issue by jimbo8098** [slomkowski/nginx-config-formatter#24]
Any issues with this being refactored to work as a library? I'm working on a project which uses this but at the moment which uses nginxfmt.py but I'd ideally like to reference this as a pip package instead, or at the very least a git package link.

**Comment by slomkowski** [comment]
Good idea. I'm planning to look at this project again since there are some issues and pull requests. There is already pip package, but not maintained by me; in near future I'm going to do the refactor and write to the maintainer to transfer ownership to me.

**Comment by jimbo8098** [comment]
Yeah I saw that pip package too (https://pypi.org/project/nginxfmt/ for those following along at home) but I would prefer to see the source of the package before using it on the project just in case something unexpected happens. I'm happy to look at PRing such an improvement if you are already planning it?

**Comment by slomkowski** [comment]
I started the implementation. For now I transferred old features. There are two classes:

* `FormatterOptions` - holds options, just indentation level for now
* `Formatter` - main class. It receives optional `FormatterOptions` and optional `logging.Logger` class

@jimbo8098 suggestions are welcome, especially regarding good Python practices since I don't use Python on daily basis.

**Comment by jimbo8098** [comment]
Excellent! I'm going to stabalise what I've got just now but I've got this in my sprint backlog to refactor into my codebase later on. I will refactor this code likely sometime in May to include the library.
